/** This file is automatically generated by generate_thunks.py. Do not edit manually!
 * 
 * This file is generated from OpenXR's xr.xml file convered by the following copyright and permission notice:
 * 
 * Copyright (c) 2017-2026 The Khronos Group Inc.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 * 
 * ------------------------------------------------------------------------
 * 
 * This file, xr.xml, is the OpenXR API Registry. It is a critically important
 * and normative part of the OpenXR Specification, including a canonical
 * machine-readable definition of the API, parameter and member validation
 * language incorporated into the Specification and reference pages, and other
 * material which is registered by Khronos, such as tags used by extension and
 * layer authors. The only authoritative version of xr.xml is the one
 * maintained in the default branch of the Khronos OpenXR GitHub project.
 *     
 */

static NTSTATUS _wine_xrDestroyInstance (struct PARAMS_xrDestroyInstance* params) {
    params->result = xrDestroyInstance(
        params->instance
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetInstanceProperties (struct PARAMS_xrGetInstanceProperties* params) {
    params->result = xrGetInstanceProperties(
        params->instance
      , params->instanceProperties
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetSystem (struct PARAMS_xrGetSystem* params) {
    params->result = xrGetSystem(
        params->instance
      , params->getInfo
      , params->systemId
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetSystemProperties (struct PARAMS_xrGetSystemProperties* params) {
    params->result = xrGetSystemProperties(
        params->instance
      , params->systemId
      , params->properties
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrCreateSession (struct PARAMS_xrCreateSession* params) {
    params->result = xrCreateSession(
        params->instance
      , params->createInfo
      , params->session
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrDestroySession (struct PARAMS_xrDestroySession* params) {
    params->result = xrDestroySession(
        params->session
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrDestroySpace (struct PARAMS_xrDestroySpace* params) {
    params->result = xrDestroySpace(
        params->space
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrDestroySwapchain (struct PARAMS_xrDestroySwapchain* params) {
    params->result = xrDestroySwapchain(
        params->swapchain
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateSwapchainImages (struct PARAMS_xrEnumerateSwapchainImages* params) {
    params->result = xrEnumerateSwapchainImages(
        params->swapchain
      , params->imageCapacityInput
      , params->imageCountOutput
      , params->images
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrAcquireSwapchainImage (struct PARAMS_xrAcquireSwapchainImage* params) {
    params->result = xrAcquireSwapchainImage(
        params->swapchain
      , params->acquireInfo
      , params->index
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrWaitSwapchainImage (struct PARAMS_xrWaitSwapchainImage* params) {
    params->result = xrWaitSwapchainImage(
        params->swapchain
      , params->waitInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrReleaseSwapchainImage (struct PARAMS_xrReleaseSwapchainImage* params) {
    params->result = xrReleaseSwapchainImage(
        params->swapchain
      , params->releaseInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrBeginSession (struct PARAMS_xrBeginSession* params) {
    params->result = xrBeginSession(
        params->session
      , params->beginInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEndSession (struct PARAMS_xrEndSession* params) {
    params->result = xrEndSession(
        params->session
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrRequestExitSession (struct PARAMS_xrRequestExitSession* params) {
    params->result = xrRequestExitSession(
        params->session
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateReferenceSpaces (struct PARAMS_xrEnumerateReferenceSpaces* params) {
    params->result = xrEnumerateReferenceSpaces(
        params->session
      , params->spaceCapacityInput
      , params->spaceCountOutput
      , params->spaces
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrCreateReferenceSpace (struct PARAMS_xrCreateReferenceSpace* params) {
    params->result = xrCreateReferenceSpace(
        params->session
      , params->createInfo
      , params->space
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrCreateActionSpace (struct PARAMS_xrCreateActionSpace* params) {
    params->result = xrCreateActionSpace(
        params->session
      , params->createInfo
      , params->space
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrLocateSpace (struct PARAMS_xrLocateSpace* params) {
    params->result = xrLocateSpace(
        params->space
      , params->baseSpace
      , params->time
      , params->location
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateViewConfigurations (struct PARAMS_xrEnumerateViewConfigurations* params) {
    params->result = xrEnumerateViewConfigurations(
        params->instance
      , params->systemId
      , params->viewConfigurationTypeCapacityInput
      , params->viewConfigurationTypeCountOutput
      , params->viewConfigurationTypes
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateEnvironmentBlendModes (struct PARAMS_xrEnumerateEnvironmentBlendModes* params) {
    params->result = xrEnumerateEnvironmentBlendModes(
        params->instance
      , params->systemId
      , params->viewConfigurationType
      , params->environmentBlendModeCapacityInput
      , params->environmentBlendModeCountOutput
      , params->environmentBlendModes
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetViewConfigurationProperties (struct PARAMS_xrGetViewConfigurationProperties* params) {
    params->result = xrGetViewConfigurationProperties(
        params->instance
      , params->systemId
      , params->viewConfigurationType
      , params->configurationProperties
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateViewConfigurationViews (struct PARAMS_xrEnumerateViewConfigurationViews* params) {
    params->result = xrEnumerateViewConfigurationViews(
        params->instance
      , params->systemId
      , params->viewConfigurationType
      , params->viewCapacityInput
      , params->viewCountOutput
      , params->views
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrBeginFrame (struct PARAMS_xrBeginFrame* params) {
    params->result = xrBeginFrame(
        params->session
      , params->frameBeginInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrLocateViews (struct PARAMS_xrLocateViews* params) {
    params->result = xrLocateViews(
        params->session
      , params->viewLocateInfo
      , params->viewState
      , params->viewCapacityInput
      , params->viewCountOutput
      , params->views
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEndFrame (struct PARAMS_xrEndFrame* params) {
    params->result = xrEndFrame(
        params->session
      , params->frameEndInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrWaitFrame (struct PARAMS_xrWaitFrame* params) {
    params->result = xrWaitFrame(
        params->session
      , params->frameWaitInfo
      , params->frameState
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrApplyHapticFeedback (struct PARAMS_xrApplyHapticFeedback* params) {
    params->result = xrApplyHapticFeedback(
        params->session
      , params->hapticActionInfo
      , params->hapticFeedback
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrStopHapticFeedback (struct PARAMS_xrStopHapticFeedback* params) {
    params->result = xrStopHapticFeedback(
        params->session
      , params->hapticActionInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrPollEvent (struct PARAMS_xrPollEvent* params) {
    params->result = xrPollEvent(
        params->instance
      , params->eventData
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrStringToPath (struct PARAMS_xrStringToPath* params) {
    params->result = xrStringToPath(
        params->instance
      , params->pathString
      , params->path
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrPathToString (struct PARAMS_xrPathToString* params) {
    params->result = xrPathToString(
        params->instance
      , params->path
      , params->bufferCapacityInput
      , params->bufferCountOutput
      , params->buffer
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetReferenceSpaceBoundsRect (struct PARAMS_xrGetReferenceSpaceBoundsRect* params) {
    params->result = xrGetReferenceSpaceBoundsRect(
        params->session
      , params->referenceSpaceType
      , params->bounds
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetActionStateBoolean (struct PARAMS_xrGetActionStateBoolean* params) {
    params->result = xrGetActionStateBoolean(
        params->session
      , params->getInfo
      , params->state
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetActionStateFloat (struct PARAMS_xrGetActionStateFloat* params) {
    params->result = xrGetActionStateFloat(
        params->session
      , params->getInfo
      , params->state
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetActionStateVector2f (struct PARAMS_xrGetActionStateVector2f* params) {
    params->result = xrGetActionStateVector2f(
        params->session
      , params->getInfo
      , params->state
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetActionStatePose (struct PARAMS_xrGetActionStatePose* params) {
    params->result = xrGetActionStatePose(
        params->session
      , params->getInfo
      , params->state
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrCreateActionSet (struct PARAMS_xrCreateActionSet* params) {
    params->result = xrCreateActionSet(
        params->instance
      , params->createInfo
      , params->actionSet
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrDestroyActionSet (struct PARAMS_xrDestroyActionSet* params) {
    params->result = xrDestroyActionSet(
        params->actionSet
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrCreateAction (struct PARAMS_xrCreateAction* params) {
    params->result = xrCreateAction(
        params->actionSet
      , params->createInfo
      , params->action
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrDestroyAction (struct PARAMS_xrDestroyAction* params) {
    params->result = xrDestroyAction(
        params->action
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrSuggestInteractionProfileBindings (struct PARAMS_xrSuggestInteractionProfileBindings* params) {
    params->result = xrSuggestInteractionProfileBindings(
        params->instance
      , params->suggestedBindings
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrAttachSessionActionSets (struct PARAMS_xrAttachSessionActionSets* params) {
    params->result = xrAttachSessionActionSets(
        params->session
      , params->attachInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetCurrentInteractionProfile (struct PARAMS_xrGetCurrentInteractionProfile* params) {
    params->result = xrGetCurrentInteractionProfile(
        params->session
      , params->topLevelUserPath
      , params->interactionProfile
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrSyncActions (struct PARAMS_xrSyncActions* params) {
    params->result = xrSyncActions(
        params->session
      , params->syncInfo
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrEnumerateBoundSourcesForAction (struct PARAMS_xrEnumerateBoundSourcesForAction* params) {
    params->result = xrEnumerateBoundSourcesForAction(
        params->session
      , params->enumerateInfo
      , params->sourceCapacityInput
      , params->sourceCountOutput
      , params->sources
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrGetInputSourceLocalizedName (struct PARAMS_xrGetInputSourceLocalizedName* params) {
    params->result = xrGetInputSourceLocalizedName(
        params->session
      , params->getInfo
      , params->bufferCapacityInput
      , params->bufferCountOutput
      , params->buffer
    );
    return STATUS_SUCCESS;
}

static NTSTATUS _wine_xrLocateSpaces (struct PARAMS_xrLocateSpaces* params) {
    params->result = xrLocateSpaces(
        params->session
      , params->locateInfo
      , params->spaceLocations
    );
    return STATUS_SUCCESS;
}

#define GENERATED_UNIX_CALLS &_wine_xrDestroyInstance, &_wine_xrGetInstanceProperties, &_wine_xrGetSystem, &_wine_xrGetSystemProperties, &_wine_xrCreateSession, &_wine_xrDestroySession, &_wine_xrDestroySpace, &_wine_xrDestroySwapchain, &_wine_xrEnumerateSwapchainImages, &_wine_xrAcquireSwapchainImage, &_wine_xrWaitSwapchainImage, &_wine_xrReleaseSwapchainImage, &_wine_xrBeginSession, &_wine_xrEndSession, &_wine_xrRequestExitSession, &_wine_xrEnumerateReferenceSpaces, &_wine_xrCreateReferenceSpace, &_wine_xrCreateActionSpace, &_wine_xrLocateSpace, &_wine_xrEnumerateViewConfigurations, &_wine_xrEnumerateEnvironmentBlendModes, &_wine_xrGetViewConfigurationProperties, &_wine_xrEnumerateViewConfigurationViews, &_wine_xrBeginFrame, &_wine_xrLocateViews, &_wine_xrEndFrame, &_wine_xrWaitFrame, &_wine_xrApplyHapticFeedback, &_wine_xrStopHapticFeedback, &_wine_xrPollEvent, &_wine_xrStringToPath, &_wine_xrPathToString, &_wine_xrGetReferenceSpaceBoundsRect, &_wine_xrGetActionStateBoolean, &_wine_xrGetActionStateFloat, &_wine_xrGetActionStateVector2f, &_wine_xrGetActionStatePose, &_wine_xrCreateActionSet, &_wine_xrDestroyActionSet, &_wine_xrCreateAction, &_wine_xrDestroyAction, &_wine_xrSuggestInteractionProfileBindings, &_wine_xrAttachSessionActionSets, &_wine_xrGetCurrentInteractionProfile, &_wine_xrSyncActions, &_wine_xrEnumerateBoundSourcesForAction, &_wine_xrGetInputSourceLocalizedName, &_wine_xrLocateSpaces
#define LAST_UNIX_CALL 55
