/** This file is automatically generated by generate_thunks.py. Do not edit manually!
 * 
 * This file is generated from OpenXR's xr.xml file convered by the following copyright and permission notice:
 * 
 * Copyright (c) 2017-2026 The Khronos Group Inc.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 * 
 * ------------------------------------------------------------------------
 * 
 * This file, xr.xml, is the OpenXR API Registry. It is a critically important
 * and normative part of the OpenXR Specification, including a canonical
 * machine-readable definition of the API, parameter and member validation
 * language incorporated into the Specification and reference pages, and other
 * material which is registered by Khronos, such as tags used by extension and
 * layer authors. The only authoritative version of xr.xml is the one
 * maintained in the default branch of the Khronos OpenXR GitHub project.
 *     
 */

struct PARAMS_xrEnumerateInstanceExtensionProperties {
    const  char *  layerName;
    uint32_t   propertyCapacityInput;
    uint32_t *  propertyCountOutput;
    XrExtensionProperties *  properties;
    XrResult result;
};

struct PARAMS_xrCreateInstance {
    const  XrInstanceCreateInfo *  createInfo;
    XrInstance *  instance;
    XrResult result;
};

struct PARAMS_xrDestroyInstance {
    XrInstance   instance;
    XrResult result;
};

struct PARAMS_xrGetInstanceProperties {
    XrInstance   instance;
    XrInstanceProperties *  instanceProperties;
    XrResult result;
};

struct PARAMS_xrGetSystem {
    XrInstance   instance;
    const  XrSystemGetInfo *  getInfo;
    XrSystemId *  systemId;
    XrResult result;
};

struct PARAMS_xrGetSystemProperties {
    XrInstance   instance;
    XrSystemId   systemId;
    XrSystemProperties *  properties;
    XrResult result;
};

struct PARAMS_xrCreateSession {
    XrInstance   instance;
    const  XrSessionCreateInfo *  createInfo;
    XrSession *  session;
    XrResult result;
};

struct PARAMS_xrDestroySession {
    XrSession   session;
    XrResult result;
};

struct PARAMS_xrDestroySpace {
    XrSpace   space;
    XrResult result;
};

struct PARAMS_xrEnumerateSwapchainFormats {
    XrSession   session;
    uint32_t   formatCapacityInput;
    uint32_t *  formatCountOutput;
    int64_t *  formats;
    XrResult result;
};

struct PARAMS_xrCreateSwapchain {
    XrSession   session;
    const  XrSwapchainCreateInfo *  createInfo;
    XrSwapchain *  swapchain;
    XrResult result;
};

struct PARAMS_xrDestroySwapchain {
    XrSwapchain   swapchain;
    XrResult result;
};

struct PARAMS_xrEnumerateSwapchainImages {
    XrSwapchain   swapchain;
    uint32_t   imageCapacityInput;
    uint32_t *  imageCountOutput;
    XrSwapchainImageBaseHeader *  images;
    XrResult result;
};

struct PARAMS_xrAcquireSwapchainImage {
    XrSwapchain   swapchain;
    const  XrSwapchainImageAcquireInfo *  acquireInfo;
    uint32_t *  index;
    XrResult result;
};

struct PARAMS_xrWaitSwapchainImage {
    XrSwapchain   swapchain;
    const  XrSwapchainImageWaitInfo *  waitInfo;
    XrResult result;
};

struct PARAMS_xrReleaseSwapchainImage {
    XrSwapchain   swapchain;
    const  XrSwapchainImageReleaseInfo *  releaseInfo;
    XrResult result;
};

struct PARAMS_xrBeginSession {
    XrSession   session;
    const  XrSessionBeginInfo *  beginInfo;
    XrResult result;
};

struct PARAMS_xrEndSession {
    XrSession   session;
    XrResult result;
};

struct PARAMS_xrRequestExitSession {
    XrSession   session;
    XrResult result;
};

struct PARAMS_xrEnumerateReferenceSpaces {
    XrSession   session;
    uint32_t   spaceCapacityInput;
    uint32_t *  spaceCountOutput;
    XrReferenceSpaceType *  spaces;
    XrResult result;
};

struct PARAMS_xrCreateReferenceSpace {
    XrSession   session;
    const  XrReferenceSpaceCreateInfo *  createInfo;
    XrSpace *  space;
    XrResult result;
};

struct PARAMS_xrCreateActionSpace {
    XrSession   session;
    const  XrActionSpaceCreateInfo *  createInfo;
    XrSpace *  space;
    XrResult result;
};

struct PARAMS_xrLocateSpace {
    XrSpace   space;
    XrSpace   baseSpace;
    XrTime   time;
    XrSpaceLocation *  location;
    XrResult result;
};

struct PARAMS_xrEnumerateViewConfigurations {
    XrInstance   instance;
    XrSystemId   systemId;
    uint32_t   viewConfigurationTypeCapacityInput;
    uint32_t *  viewConfigurationTypeCountOutput;
    XrViewConfigurationType *  viewConfigurationTypes;
    XrResult result;
};

struct PARAMS_xrEnumerateEnvironmentBlendModes {
    XrInstance   instance;
    XrSystemId   systemId;
    XrViewConfigurationType   viewConfigurationType;
    uint32_t   environmentBlendModeCapacityInput;
    uint32_t *  environmentBlendModeCountOutput;
    XrEnvironmentBlendMode *  environmentBlendModes;
    XrResult result;
};

struct PARAMS_xrGetViewConfigurationProperties {
    XrInstance   instance;
    XrSystemId   systemId;
    XrViewConfigurationType   viewConfigurationType;
    XrViewConfigurationProperties *  configurationProperties;
    XrResult result;
};

struct PARAMS_xrEnumerateViewConfigurationViews {
    XrInstance   instance;
    XrSystemId   systemId;
    XrViewConfigurationType   viewConfigurationType;
    uint32_t   viewCapacityInput;
    uint32_t *  viewCountOutput;
    XrViewConfigurationView *  views;
    XrResult result;
};

struct PARAMS_xrBeginFrame {
    XrSession   session;
    const  XrFrameBeginInfo *  frameBeginInfo;
    XrResult result;
};

struct PARAMS_xrLocateViews {
    XrSession   session;
    const  XrViewLocateInfo *  viewLocateInfo;
    XrViewState *  viewState;
    uint32_t   viewCapacityInput;
    uint32_t *  viewCountOutput;
    XrView *  views;
    XrResult result;
};

struct PARAMS_xrEndFrame {
    XrSession   session;
    const  XrFrameEndInfo *  frameEndInfo;
    XrResult result;
};

struct PARAMS_xrWaitFrame {
    XrSession   session;
    const  XrFrameWaitInfo *  frameWaitInfo;
    XrFrameState *  frameState;
    XrResult result;
};

struct PARAMS_xrApplyHapticFeedback {
    XrSession   session;
    const  XrHapticActionInfo *  hapticActionInfo;
    const  XrHapticBaseHeader *  hapticFeedback;
    XrResult result;
};

struct PARAMS_xrStopHapticFeedback {
    XrSession   session;
    const  XrHapticActionInfo *  hapticActionInfo;
    XrResult result;
};

struct PARAMS_xrPollEvent {
    XrInstance   instance;
    XrEventDataBuffer *  eventData;
    XrResult result;
};

struct PARAMS_xrStringToPath {
    XrInstance   instance;
    const  char *  pathString;
    XrPath *  path;
    XrResult result;
};

struct PARAMS_xrPathToString {
    XrInstance   instance;
    XrPath   path;
    uint32_t   bufferCapacityInput;
    uint32_t *  bufferCountOutput;
    char *  buffer;
    XrResult result;
};

struct PARAMS_xrGetReferenceSpaceBoundsRect {
    XrSession   session;
    XrReferenceSpaceType   referenceSpaceType;
    XrExtent2Df *  bounds;
    XrResult result;
};

struct PARAMS_xrGetActionStateBoolean {
    XrSession   session;
    const  XrActionStateGetInfo *  getInfo;
    XrActionStateBoolean *  state;
    XrResult result;
};

struct PARAMS_xrGetActionStateFloat {
    XrSession   session;
    const  XrActionStateGetInfo *  getInfo;
    XrActionStateFloat *  state;
    XrResult result;
};

struct PARAMS_xrGetActionStateVector2f {
    XrSession   session;
    const  XrActionStateGetInfo *  getInfo;
    XrActionStateVector2f *  state;
    XrResult result;
};

struct PARAMS_xrGetActionStatePose {
    XrSession   session;
    const  XrActionStateGetInfo *  getInfo;
    XrActionStatePose *  state;
    XrResult result;
};

struct PARAMS_xrCreateActionSet {
    XrInstance   instance;
    const  XrActionSetCreateInfo *  createInfo;
    XrActionSet *  actionSet;
    XrResult result;
};

struct PARAMS_xrDestroyActionSet {
    XrActionSet   actionSet;
    XrResult result;
};

struct PARAMS_xrCreateAction {
    XrActionSet   actionSet;
    const  XrActionCreateInfo *  createInfo;
    XrAction *  action;
    XrResult result;
};

struct PARAMS_xrDestroyAction {
    XrAction   action;
    XrResult result;
};

struct PARAMS_xrSuggestInteractionProfileBindings {
    XrInstance   instance;
    const  XrInteractionProfileSuggestedBinding *  suggestedBindings;
    XrResult result;
};

struct PARAMS_xrAttachSessionActionSets {
    XrSession   session;
    const  XrSessionActionSetsAttachInfo *  attachInfo;
    XrResult result;
};

struct PARAMS_xrGetCurrentInteractionProfile {
    XrSession   session;
    XrPath   topLevelUserPath;
    XrInteractionProfileState *  interactionProfile;
    XrResult result;
};

struct PARAMS_xrSyncActions {
    XrSession   session;
    const  XrActionsSyncInfo *  syncInfo;
    XrResult result;
};

struct PARAMS_xrEnumerateBoundSourcesForAction {
    XrSession   session;
    const  XrBoundSourcesForActionEnumerateInfo *  enumerateInfo;
    uint32_t   sourceCapacityInput;
    uint32_t *  sourceCountOutput;
    XrPath *  sources;
    XrResult result;
};

struct PARAMS_xrGetInputSourceLocalizedName {
    XrSession   session;
    const  XrInputSourceLocalizedNameGetInfo *  getInfo;
    uint32_t   bufferCapacityInput;
    uint32_t *  bufferCountOutput;
    char *  buffer;
    XrResult result;
};

struct PARAMS_xrLocateSpaces {
    XrSession   session;
    const  XrSpacesLocateInfo *  locateInfo;
    XrSpaceLocations *  spaceLocations;
    XrResult result;
};

