/** This file is automatically generated by generate_thunks.py. Do not edit manually!
 * 
 * This file is generated from OpenXR's xr.xml file convered by the following copyright and permission notice:
 * 
 * Copyright (c) 2017-2026 The Khronos Group Inc.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 * 
 * ------------------------------------------------------------------------
 * 
 * This file, xr.xml, is the OpenXR API Registry. It is a critically important
 * and normative part of the OpenXR Specification, including a canonical
 * machine-readable definition of the API, parameter and member validation
 * language incorporated into the Specification and reference pages, and other
 * material which is registered by Khronos, such as tags used by extension and
 * layer authors. The only authoritative version of xr.xml is the one
 * maintained in the default branch of the Khronos OpenXR GitHub project.
 *     
 */

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateInstanceExtensionProperties(
    const  char *  layerName
  , uint32_t   propertyCapacityInput
  , uint32_t *  propertyCountOutput
  , XrExtensionProperties *  properties
) {
    struct PARAMS_xrEnumerateInstanceExtensionProperties params = {
        .layerName = layerName, 
        .propertyCapacityInput = propertyCapacityInput, 
        .propertyCountOutput = propertyCountOutput, 
        .properties = properties, 
    };
    NTSTATUS res = UNIX_CALL(3, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateInstance(
    const  XrInstanceCreateInfo *  createInfo
  , XrInstance *  instance
) {
    struct PARAMS_xrCreateInstance params = {
        .createInfo = createInfo, 
        .instance = instance, 
    };
    NTSTATUS res = UNIX_CALL(4, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroyInstance(
    XrInstance   instance
) {
    struct PARAMS_xrDestroyInstance params = {
        .instance = instance, 
    };
    NTSTATUS res = UNIX_CALL(6, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetInstanceProperties(
    XrInstance   instance
  , XrInstanceProperties *  instanceProperties
) {
    struct PARAMS_xrGetInstanceProperties params = {
        .instance = instance, 
        .instanceProperties = instanceProperties, 
    };
    NTSTATUS res = UNIX_CALL(7, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetSystem(
    XrInstance   instance
  , const  XrSystemGetInfo *  getInfo
  , XrSystemId *  systemId
) {
    struct PARAMS_xrGetSystem params = {
        .instance = instance, 
        .getInfo = getInfo, 
        .systemId = systemId, 
    };
    NTSTATUS res = UNIX_CALL(8, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetSystemProperties(
    XrInstance   instance
  , XrSystemId   systemId
  , XrSystemProperties *  properties
) {
    struct PARAMS_xrGetSystemProperties params = {
        .instance = instance, 
        .systemId = systemId, 
        .properties = properties, 
    };
    NTSTATUS res = UNIX_CALL(9, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateSession(
    XrInstance   instance
  , const  XrSessionCreateInfo *  createInfo
  , XrSession *  session
) {
    struct PARAMS_xrCreateSession params = {
        .instance = instance, 
        .createInfo = createInfo, 
        .session = session, 
    };
    NTSTATUS res = UNIX_CALL(10, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroySession(
    XrSession   session
) {
    struct PARAMS_xrDestroySession params = {
        .session = session, 
    };
    NTSTATUS res = UNIX_CALL(11, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroySpace(
    XrSpace   space
) {
    struct PARAMS_xrDestroySpace params = {
        .space = space, 
    };
    NTSTATUS res = UNIX_CALL(12, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateSwapchainFormats(
    XrSession   session
  , uint32_t   formatCapacityInput
  , uint32_t *  formatCountOutput
  , int64_t *  formats
) {
    struct PARAMS_xrEnumerateSwapchainFormats params = {
        .session = session, 
        .formatCapacityInput = formatCapacityInput, 
        .formatCountOutput = formatCountOutput, 
        .formats = formats, 
    };
    NTSTATUS res = UNIX_CALL(13, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateSwapchain(
    XrSession   session
  , const  XrSwapchainCreateInfo *  createInfo
  , XrSwapchain *  swapchain
) {
    struct PARAMS_xrCreateSwapchain params = {
        .session = session, 
        .createInfo = createInfo, 
        .swapchain = swapchain, 
    };
    NTSTATUS res = UNIX_CALL(14, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroySwapchain(
    XrSwapchain   swapchain
) {
    struct PARAMS_xrDestroySwapchain params = {
        .swapchain = swapchain, 
    };
    NTSTATUS res = UNIX_CALL(15, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateSwapchainImages(
    XrSwapchain   swapchain
  , uint32_t   imageCapacityInput
  , uint32_t *  imageCountOutput
  , XrSwapchainImageBaseHeader *  images
) {
    struct PARAMS_xrEnumerateSwapchainImages params = {
        .swapchain = swapchain, 
        .imageCapacityInput = imageCapacityInput, 
        .imageCountOutput = imageCountOutput, 
        .images = images, 
    };
    NTSTATUS res = UNIX_CALL(16, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrAcquireSwapchainImage(
    XrSwapchain   swapchain
  , const  XrSwapchainImageAcquireInfo *  acquireInfo
  , uint32_t *  index
) {
    struct PARAMS_xrAcquireSwapchainImage params = {
        .swapchain = swapchain, 
        .acquireInfo = acquireInfo, 
        .index = index, 
    };
    NTSTATUS res = UNIX_CALL(17, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrWaitSwapchainImage(
    XrSwapchain   swapchain
  , const  XrSwapchainImageWaitInfo *  waitInfo
) {
    struct PARAMS_xrWaitSwapchainImage params = {
        .swapchain = swapchain, 
        .waitInfo = waitInfo, 
    };
    NTSTATUS res = UNIX_CALL(18, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrReleaseSwapchainImage(
    XrSwapchain   swapchain
  , const  XrSwapchainImageReleaseInfo *  releaseInfo
) {
    struct PARAMS_xrReleaseSwapchainImage params = {
        .swapchain = swapchain, 
        .releaseInfo = releaseInfo, 
    };
    NTSTATUS res = UNIX_CALL(19, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrBeginSession(
    XrSession   session
  , const  XrSessionBeginInfo *  beginInfo
) {
    struct PARAMS_xrBeginSession params = {
        .session = session, 
        .beginInfo = beginInfo, 
    };
    NTSTATUS res = UNIX_CALL(20, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEndSession(
    XrSession   session
) {
    struct PARAMS_xrEndSession params = {
        .session = session, 
    };
    NTSTATUS res = UNIX_CALL(21, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrRequestExitSession(
    XrSession   session
) {
    struct PARAMS_xrRequestExitSession params = {
        .session = session, 
    };
    NTSTATUS res = UNIX_CALL(22, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateReferenceSpaces(
    XrSession   session
  , uint32_t   spaceCapacityInput
  , uint32_t *  spaceCountOutput
  , XrReferenceSpaceType *  spaces
) {
    struct PARAMS_xrEnumerateReferenceSpaces params = {
        .session = session, 
        .spaceCapacityInput = spaceCapacityInput, 
        .spaceCountOutput = spaceCountOutput, 
        .spaces = spaces, 
    };
    NTSTATUS res = UNIX_CALL(23, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateReferenceSpace(
    XrSession   session
  , const  XrReferenceSpaceCreateInfo *  createInfo
  , XrSpace *  space
) {
    struct PARAMS_xrCreateReferenceSpace params = {
        .session = session, 
        .createInfo = createInfo, 
        .space = space, 
    };
    NTSTATUS res = UNIX_CALL(24, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateActionSpace(
    XrSession   session
  , const  XrActionSpaceCreateInfo *  createInfo
  , XrSpace *  space
) {
    struct PARAMS_xrCreateActionSpace params = {
        .session = session, 
        .createInfo = createInfo, 
        .space = space, 
    };
    NTSTATUS res = UNIX_CALL(25, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrLocateSpace(
    XrSpace   space
  , XrSpace   baseSpace
  , XrTime   time
  , XrSpaceLocation *  location
) {
    struct PARAMS_xrLocateSpace params = {
        .space = space, 
        .baseSpace = baseSpace, 
        .time = time, 
        .location = location, 
    };
    NTSTATUS res = UNIX_CALL(26, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateViewConfigurations(
    XrInstance   instance
  , XrSystemId   systemId
  , uint32_t   viewConfigurationTypeCapacityInput
  , uint32_t *  viewConfigurationTypeCountOutput
  , XrViewConfigurationType *  viewConfigurationTypes
) {
    struct PARAMS_xrEnumerateViewConfigurations params = {
        .instance = instance, 
        .systemId = systemId, 
        .viewConfigurationTypeCapacityInput = viewConfigurationTypeCapacityInput, 
        .viewConfigurationTypeCountOutput = viewConfigurationTypeCountOutput, 
        .viewConfigurationTypes = viewConfigurationTypes, 
    };
    NTSTATUS res = UNIX_CALL(27, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateEnvironmentBlendModes(
    XrInstance   instance
  , XrSystemId   systemId
  , XrViewConfigurationType   viewConfigurationType
  , uint32_t   environmentBlendModeCapacityInput
  , uint32_t *  environmentBlendModeCountOutput
  , XrEnvironmentBlendMode *  environmentBlendModes
) {
    struct PARAMS_xrEnumerateEnvironmentBlendModes params = {
        .instance = instance, 
        .systemId = systemId, 
        .viewConfigurationType = viewConfigurationType, 
        .environmentBlendModeCapacityInput = environmentBlendModeCapacityInput, 
        .environmentBlendModeCountOutput = environmentBlendModeCountOutput, 
        .environmentBlendModes = environmentBlendModes, 
    };
    NTSTATUS res = UNIX_CALL(28, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetViewConfigurationProperties(
    XrInstance   instance
  , XrSystemId   systemId
  , XrViewConfigurationType   viewConfigurationType
  , XrViewConfigurationProperties *  configurationProperties
) {
    struct PARAMS_xrGetViewConfigurationProperties params = {
        .instance = instance, 
        .systemId = systemId, 
        .viewConfigurationType = viewConfigurationType, 
        .configurationProperties = configurationProperties, 
    };
    NTSTATUS res = UNIX_CALL(29, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateViewConfigurationViews(
    XrInstance   instance
  , XrSystemId   systemId
  , XrViewConfigurationType   viewConfigurationType
  , uint32_t   viewCapacityInput
  , uint32_t *  viewCountOutput
  , XrViewConfigurationView *  views
) {
    struct PARAMS_xrEnumerateViewConfigurationViews params = {
        .instance = instance, 
        .systemId = systemId, 
        .viewConfigurationType = viewConfigurationType, 
        .viewCapacityInput = viewCapacityInput, 
        .viewCountOutput = viewCountOutput, 
        .views = views, 
    };
    NTSTATUS res = UNIX_CALL(30, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrBeginFrame(
    XrSession   session
  , const  XrFrameBeginInfo *  frameBeginInfo
) {
    struct PARAMS_xrBeginFrame params = {
        .session = session, 
        .frameBeginInfo = frameBeginInfo, 
    };
    NTSTATUS res = UNIX_CALL(31, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrLocateViews(
    XrSession   session
  , const  XrViewLocateInfo *  viewLocateInfo
  , XrViewState *  viewState
  , uint32_t   viewCapacityInput
  , uint32_t *  viewCountOutput
  , XrView *  views
) {
    struct PARAMS_xrLocateViews params = {
        .session = session, 
        .viewLocateInfo = viewLocateInfo, 
        .viewState = viewState, 
        .viewCapacityInput = viewCapacityInput, 
        .viewCountOutput = viewCountOutput, 
        .views = views, 
    };
    NTSTATUS res = UNIX_CALL(32, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEndFrame(
    XrSession   session
  , const  XrFrameEndInfo *  frameEndInfo
) {
    struct PARAMS_xrEndFrame params = {
        .session = session, 
        .frameEndInfo = frameEndInfo, 
    };
    NTSTATUS res = UNIX_CALL(33, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrWaitFrame(
    XrSession   session
  , const  XrFrameWaitInfo *  frameWaitInfo
  , XrFrameState *  frameState
) {
    struct PARAMS_xrWaitFrame params = {
        .session = session, 
        .frameWaitInfo = frameWaitInfo, 
        .frameState = frameState, 
    };
    NTSTATUS res = UNIX_CALL(34, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrApplyHapticFeedback(
    XrSession   session
  , const  XrHapticActionInfo *  hapticActionInfo
  , const  XrHapticBaseHeader *  hapticFeedback
) {
    struct PARAMS_xrApplyHapticFeedback params = {
        .session = session, 
        .hapticActionInfo = hapticActionInfo, 
        .hapticFeedback = hapticFeedback, 
    };
    NTSTATUS res = UNIX_CALL(35, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrStopHapticFeedback(
    XrSession   session
  , const  XrHapticActionInfo *  hapticActionInfo
) {
    struct PARAMS_xrStopHapticFeedback params = {
        .session = session, 
        .hapticActionInfo = hapticActionInfo, 
    };
    NTSTATUS res = UNIX_CALL(36, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrPollEvent(
    XrInstance   instance
  , XrEventDataBuffer *  eventData
) {
    struct PARAMS_xrPollEvent params = {
        .instance = instance, 
        .eventData = eventData, 
    };
    NTSTATUS res = UNIX_CALL(37, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrStringToPath(
    XrInstance   instance
  , const  char *  pathString
  , XrPath *  path
) {
    struct PARAMS_xrStringToPath params = {
        .instance = instance, 
        .pathString = pathString, 
        .path = path, 
    };
    NTSTATUS res = UNIX_CALL(38, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrPathToString(
    XrInstance   instance
  , XrPath   path
  , uint32_t   bufferCapacityInput
  , uint32_t *  bufferCountOutput
  , char *  buffer
) {
    struct PARAMS_xrPathToString params = {
        .instance = instance, 
        .path = path, 
        .bufferCapacityInput = bufferCapacityInput, 
        .bufferCountOutput = bufferCountOutput, 
        .buffer = buffer, 
    };
    NTSTATUS res = UNIX_CALL(39, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetReferenceSpaceBoundsRect(
    XrSession   session
  , XrReferenceSpaceType   referenceSpaceType
  , XrExtent2Df *  bounds
) {
    struct PARAMS_xrGetReferenceSpaceBoundsRect params = {
        .session = session, 
        .referenceSpaceType = referenceSpaceType, 
        .bounds = bounds, 
    };
    NTSTATUS res = UNIX_CALL(40, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetActionStateBoolean(
    XrSession   session
  , const  XrActionStateGetInfo *  getInfo
  , XrActionStateBoolean *  state
) {
    struct PARAMS_xrGetActionStateBoolean params = {
        .session = session, 
        .getInfo = getInfo, 
        .state = state, 
    };
    NTSTATUS res = UNIX_CALL(41, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetActionStateFloat(
    XrSession   session
  , const  XrActionStateGetInfo *  getInfo
  , XrActionStateFloat *  state
) {
    struct PARAMS_xrGetActionStateFloat params = {
        .session = session, 
        .getInfo = getInfo, 
        .state = state, 
    };
    NTSTATUS res = UNIX_CALL(42, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetActionStateVector2f(
    XrSession   session
  , const  XrActionStateGetInfo *  getInfo
  , XrActionStateVector2f *  state
) {
    struct PARAMS_xrGetActionStateVector2f params = {
        .session = session, 
        .getInfo = getInfo, 
        .state = state, 
    };
    NTSTATUS res = UNIX_CALL(43, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetActionStatePose(
    XrSession   session
  , const  XrActionStateGetInfo *  getInfo
  , XrActionStatePose *  state
) {
    struct PARAMS_xrGetActionStatePose params = {
        .session = session, 
        .getInfo = getInfo, 
        .state = state, 
    };
    NTSTATUS res = UNIX_CALL(44, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateActionSet(
    XrInstance   instance
  , const  XrActionSetCreateInfo *  createInfo
  , XrActionSet *  actionSet
) {
    struct PARAMS_xrCreateActionSet params = {
        .instance = instance, 
        .createInfo = createInfo, 
        .actionSet = actionSet, 
    };
    NTSTATUS res = UNIX_CALL(45, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroyActionSet(
    XrActionSet   actionSet
) {
    struct PARAMS_xrDestroyActionSet params = {
        .actionSet = actionSet, 
    };
    NTSTATUS res = UNIX_CALL(46, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrCreateAction(
    XrActionSet   actionSet
  , const  XrActionCreateInfo *  createInfo
  , XrAction *  action
) {
    struct PARAMS_xrCreateAction params = {
        .actionSet = actionSet, 
        .createInfo = createInfo, 
        .action = action, 
    };
    NTSTATUS res = UNIX_CALL(47, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrDestroyAction(
    XrAction   action
) {
    struct PARAMS_xrDestroyAction params = {
        .action = action, 
    };
    NTSTATUS res = UNIX_CALL(48, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrSuggestInteractionProfileBindings(
    XrInstance   instance
  , const  XrInteractionProfileSuggestedBinding *  suggestedBindings
) {
    struct PARAMS_xrSuggestInteractionProfileBindings params = {
        .instance = instance, 
        .suggestedBindings = suggestedBindings, 
    };
    NTSTATUS res = UNIX_CALL(49, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrAttachSessionActionSets(
    XrSession   session
  , const  XrSessionActionSetsAttachInfo *  attachInfo
) {
    struct PARAMS_xrAttachSessionActionSets params = {
        .session = session, 
        .attachInfo = attachInfo, 
    };
    NTSTATUS res = UNIX_CALL(50, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetCurrentInteractionProfile(
    XrSession   session
  , XrPath   topLevelUserPath
  , XrInteractionProfileState *  interactionProfile
) {
    struct PARAMS_xrGetCurrentInteractionProfile params = {
        .session = session, 
        .topLevelUserPath = topLevelUserPath, 
        .interactionProfile = interactionProfile, 
    };
    NTSTATUS res = UNIX_CALL(51, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrSyncActions(
    XrSession   session
  , const  XrActionsSyncInfo *  syncInfo
) {
    struct PARAMS_xrSyncActions params = {
        .session = session, 
        .syncInfo = syncInfo, 
    };
    NTSTATUS res = UNIX_CALL(52, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrEnumerateBoundSourcesForAction(
    XrSession   session
  , const  XrBoundSourcesForActionEnumerateInfo *  enumerateInfo
  , uint32_t   sourceCapacityInput
  , uint32_t *  sourceCountOutput
  , XrPath *  sources
) {
    struct PARAMS_xrEnumerateBoundSourcesForAction params = {
        .session = session, 
        .enumerateInfo = enumerateInfo, 
        .sourceCapacityInput = sourceCapacityInput, 
        .sourceCountOutput = sourceCountOutput, 
        .sources = sources, 
    };
    NTSTATUS res = UNIX_CALL(53, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrGetInputSourceLocalizedName(
    XrSession   session
  , const  XrInputSourceLocalizedNameGetInfo *  getInfo
  , uint32_t   bufferCapacityInput
  , uint32_t *  bufferCountOutput
  , char *  buffer
) {
    struct PARAMS_xrGetInputSourceLocalizedName params = {
        .session = session, 
        .getInfo = getInfo, 
        .bufferCapacityInput = bufferCapacityInput, 
        .bufferCountOutput = bufferCountOutput, 
        .buffer = buffer, 
    };
    NTSTATUS res = UNIX_CALL(54, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

XRAPI_ATTR XrResult XRAPI_CALL wine_xrLocateSpaces(
    XrSession   session
  , const  XrSpacesLocateInfo *  locateInfo
  , XrSpaceLocations *  spaceLocations
) {
    struct PARAMS_xrLocateSpaces params = {
        .session = session, 
        .locateInfo = locateInfo, 
        .spaceLocations = spaceLocations, 
    };
    NTSTATUS res = UNIX_CALL(55, &params);
    if (res != STATUS_SUCCESS) return XR_ERROR_RUNTIME_FAILURE;
    return params.result;
}

static inline XrResult wine_xrGetInstanceProcAddr(XrInstance instance, const char* name, PFN_xrVoidFunction* function) {
    if (strcmp(name, "xrEnumerateInstanceExtensionProperties") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateInstanceExtensionProperties;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateInstance") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateInstance;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroyInstance") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroyInstance;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetInstanceProperties") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetInstanceProperties;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetSystem") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetSystem;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetSystemProperties") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetSystemProperties;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateSession") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateSession;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroySession") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroySession;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroySpace") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroySpace;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateSwapchainFormats") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateSwapchainFormats;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateSwapchain") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateSwapchain;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroySwapchain") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroySwapchain;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateSwapchainImages") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateSwapchainImages;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrAcquireSwapchainImage") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrAcquireSwapchainImage;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrWaitSwapchainImage") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrWaitSwapchainImage;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrReleaseSwapchainImage") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrReleaseSwapchainImage;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrBeginSession") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrBeginSession;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEndSession") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEndSession;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrRequestExitSession") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrRequestExitSession;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateReferenceSpaces") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateReferenceSpaces;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateReferenceSpace") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateReferenceSpace;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateActionSpace") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateActionSpace;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrLocateSpace") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrLocateSpace;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateViewConfigurations") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateViewConfigurations;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateEnvironmentBlendModes") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateEnvironmentBlendModes;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetViewConfigurationProperties") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetViewConfigurationProperties;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateViewConfigurationViews") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateViewConfigurationViews;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrBeginFrame") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrBeginFrame;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrLocateViews") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrLocateViews;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEndFrame") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEndFrame;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrWaitFrame") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrWaitFrame;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrApplyHapticFeedback") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrApplyHapticFeedback;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrStopHapticFeedback") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrStopHapticFeedback;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrPollEvent") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrPollEvent;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrStringToPath") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrStringToPath;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrPathToString") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrPathToString;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetReferenceSpaceBoundsRect") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetReferenceSpaceBoundsRect;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetActionStateBoolean") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetActionStateBoolean;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetActionStateFloat") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetActionStateFloat;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetActionStateVector2f") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetActionStateVector2f;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetActionStatePose") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetActionStatePose;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateActionSet") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateActionSet;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroyActionSet") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroyActionSet;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrCreateAction") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrCreateAction;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrDestroyAction") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrDestroyAction;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrSuggestInteractionProfileBindings") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrSuggestInteractionProfileBindings;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrAttachSessionActionSets") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrAttachSessionActionSets;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetCurrentInteractionProfile") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetCurrentInteractionProfile;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrSyncActions") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrSyncActions;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrEnumerateBoundSourcesForAction") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrEnumerateBoundSourcesForAction;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrGetInputSourceLocalizedName") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrGetInputSourceLocalizedName;
        return XR_SUCCESS;
    }
    if (strcmp(name, "xrLocateSpaces") == 0) {
        *function = (PFN_xrVoidFunction)&wine_xrLocateSpaces;
        return XR_SUCCESS;
    }
    return XR_ERROR_FUNCTION_UNSUPPORTED;
}